### ISSUE TITLE
please help error in summary api

### ISSUE THREAD

**Issue by andikapri2020** [eyelevelai/groundx-on-prem#7]
Hello All,

I have deployed groundx in kubernetes cluster on prem,.

and I get this issues :

1. I tried feature crawl_website, I get status training in queue process id , below are the response:
{
 "ingest": {
  "processId": "952eadf6-c90c-48e4-95f6-0c3a59222ac4",
  "status": "training"
 }
}

If this expected or not ? I read the Website official the status of queue only :
queued
processing
error
complete
cancelled 

2. error in summary-api, the following is the error:

[2024-12-20 09:14:53 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-20 09:14:53 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2024-12-20 09:14:53 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-12-20 09:14:53 +0000] [7] [INFO] Booting worker with pid: 7
[2024-12-20 09:14:53 +0000] [8] [INFO] Booting worker with pid: 8
2024-12-20 09:14:53,350 - [7] - ERROR - Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/summary_server.py", line 32, in <module>
    service=env["service"],
            ~~~^^^^^^^^^^^
KeyError: 'service'

anyone can help this problem?

Thank you .

**Comment by blfletcher** [comment]
@andikapri2020 thanks for reporting this bug.

we did not document this but crawl_website is currently not supported for on prem. we are adding an error message for requests of this type to a future release.

the downstream error trace you shared can be corrected by redeploying the summary service. you can do that using the build scripts with the following commands.

to uninstall the summary service:
```
bin/operator summary -c
```

to re-install the summary service with updated pod containers:
```
bin/operator summary
```

**Comment by andikapri2020** [comment]
@blfletcher thank you so much for your solutions.

currently, summary service already running properly.

Thank you.
